# -*- coding: utf-8 -*-
"""Copy of 1. kg to g Convertor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZTLk0FnAj8LblIXK7kJkGs1MCocOoy7t
"""

kg = input("Please inter kg:")
g = kg * 1000
print ("g =", g )